.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Steve Sixty-Four <steve8x8@googlemail.com>
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MC-EXTFS-ADB 1 "September 22, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mc-extfs-adb \- adb and adbsu VFS modules for Midnight Commander
.SH SYNOPSIS
.B adb://, adbsu://
.SH DESCRIPTION
This manual page documents briefly the
.B adb
and
.B adbsu
VFS modules.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.SH OPTIONS
These modules can be used in a MC context, by changing to a virtual 
directory tree using
.B cd adb://
or
.B cd adbsu://
.PP
The difference between both methods is that \fBadbsu\fR uses \fIsu\fR
for filesystem access and sees all files, directories and links while
\fBadb\fR may not.
.SH SEE ALSO
.BR mc (1)
.br
